type Project {
  title: String!
  summary: String!
  githubUrl: String!
  siteUrl: String
  keyTasks: [String!]!
  tech: [String!]!
  date: Date!
  asset: Asset!
}

type Asset {
  id: String!
  url: String!
  type: String
  cloudName: String!
}

type Query {
  allProjects: [Project!]!
}
